### ISSUE TITLE
Redundant for loops

### ISSUE THREAD

**Issue by 0x3a2d50** [jahhweh/KFF#2]
These for loops: https://github.com/jahhweh/KFF/blob/main/contracts/KFF.sol#L54-L71 can be rewritten as a single loop

**Comment by 0x3a2d50** [comment]
You can also reduce the redundant tokenId calculations by setting the tokenId in memory and using it as the parameter for `_safeMint` and index for `hodlStart`, `ranking`, and `roles`

**Comment by jahhweh** [comment]
quick fix, rewritten as single loop
